import javax.swing.JOptionPane;

public class AddNewEmployee_jFrame extends javax.swing.JFrame {
    
    private MyHashTable mainHT;  // This contains the ref value for theHT of MainJFrame.

    //Creates new form AddNewEmployeeJFrame
    public AddNewEmployee_jFrame() {
        initComponents();
             
        //jLabel4.setVisible(false); // Hide the Added new employee message
        
        fullTimeInternalFrame.setVisible(false);  // Hide the FTE internal jFrame
        partTimeInternalFrame.setVisible(false);  // Hide the PTE internal jFrame        
        
        //ButtonGroup group = new ButtonGroup();
        
        pack();
    }
    
    
    public void setMainHT(MyHashTable theRefVal) {
        mainHT = theRefVal;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        empNumLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        lastNameLabel = new javax.swing.JLabel();
        empNumText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        fullTimeButton = new javax.swing.JRadioButton();
        partTimeButton = new javax.swing.JRadioButton();
        fullTimeInternalFrame = new javax.swing.JInternalFrame();
        annualSalaryLabel = new javax.swing.JLabel();
        annualSalaryText = new javax.swing.JTextField();
        fullTimeDRLabel = new javax.swing.JLabel();
        fuillTimeDRText = new javax.swing.JTextField();
        partTimeInternalFrame = new javax.swing.JInternalFrame();
        hWLabel = new javax.swing.JLabel();
        hPWLabel = new javax.swing.JLabel();
        wPYLabel = new javax.swing.JLabel();
        hWText = new javax.swing.JTextField();
        hPWText = new javax.swing.JTextField();
        wPYText = new javax.swing.JTextField();
        partTimeDRLabel = new javax.swing.JLabel();
        partTimeDRText = new javax.swing.JTextField();
        firstNameText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        empNumLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        empNumLabel.setText("Employee Number");
        empNumLabel.setToolTipText("Enter a six digit employee number (e.g. 123456)");

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        firstNameLabel.setText("First Name");

        lastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lastNameLabel.setText("Last Name");

        empNumText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        empNumText.setToolTipText("Enter a six digit employee number (e.g. 123456)");
        empNumText.setMinimumSize(new java.awt.Dimension(60, 20));

        lastNameText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lastNameText.setMinimumSize(new java.awt.Dimension(60, 20));

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTheNewEmployee(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitAddNewEmployee(evt);
            }
        });

        buttonGroup1.add(fullTimeButton);
        fullTimeButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        fullTimeButton.setText("Full time");
        fullTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTERadioButtonClicked(evt);
            }
        });

        buttonGroup1.add(partTimeButton);
        partTimeButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        partTimeButton.setText("Part time");
        partTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTERadioButtonClicked(evt);
            }
        });

        fullTimeInternalFrame.setVisible(true);

        annualSalaryLabel.setText("Annual Salary");

        annualSalaryText.setToolTipText("Gross Annual Salary");

        fullTimeDRLabel.setText("Deduction Rate");

        javax.swing.GroupLayout fullTimeInternalFrameLayout = new javax.swing.GroupLayout(fullTimeInternalFrame.getContentPane());
        fullTimeInternalFrame.getContentPane().setLayout(fullTimeInternalFrameLayout);
        fullTimeInternalFrameLayout.setHorizontalGroup(
            fullTimeInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullTimeInternalFrameLayout.createSequentialGroup()
                .addGroup(fullTimeInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fullTimeInternalFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(annualSalaryLabel)
                        .addGap(18, 18, 18)
                        .addComponent(annualSalaryText, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fullTimeInternalFrameLayout.createSequentialGroup()
                        .addComponent(fullTimeDRLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fuillTimeDRText, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        fullTimeInternalFrameLayout.setVerticalGroup(
            fullTimeInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fullTimeInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fullTimeInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annualSalaryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(annualSalaryLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fullTimeInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fullTimeDRLabel)
                    .addComponent(fuillTimeDRText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        partTimeInternalFrame.setVisible(true);

        hWLabel.setText("Hourly wage");

        hPWLabel.setText("Hours per week");

        wPYLabel.setText("Weeks per year");

        partTimeDRLabel.setText("Deduction Rate");

        javax.swing.GroupLayout partTimeInternalFrameLayout = new javax.swing.GroupLayout(partTimeInternalFrame.getContentPane());
        partTimeInternalFrame.getContentPane().setLayout(partTimeInternalFrameLayout);
        partTimeInternalFrameLayout.setHorizontalGroup(
            partTimeInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partTimeInternalFrameLayout.createSequentialGroup()
                .addGroup(partTimeInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(partTimeInternalFrameLayout.createSequentialGroup()
                        .addGroup(partTimeInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(partTimeInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(wPYLabel)
                                .addComponent(hPWLabel))
                            .addGroup(partTimeInternalFrameLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(hWLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(partTimeInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hPWText, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(wPYText)
                            .addComponent(hWText)))
                    .addGroup(partTimeInternalFrameLayout.createSequentialGroup()
                        .addComponent(partTimeDRLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(partTimeDRText)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        partTimeInternalFrameLayout.setVerticalGroup(
            partTimeInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(partTimeInternalFrameLayout.createSequentialGroup()
                .addGroup(partTimeInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hWLabel)
                    .addComponent(hWText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(partTimeInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hPWLabel)
                    .addComponent(hPWText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(partTimeInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wPYLabel)
                    .addComponent(wPYText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(partTimeInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeDRLabel)
                    .addComponent(partTimeDRText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        firstNameText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(partTimeButton)
                            .addComponent(lastNameLabel)
                            .addComponent(firstNameLabel)
                            .addComponent(empNumLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(empNumText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lastNameText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fullTimeButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(partTimeInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fullTimeInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 260, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(addButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(exitButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNumLabel)
                    .addComponent(empNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeButton)
                    .addComponent(fullTimeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fullTimeInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partTimeInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(exitButton))
                .addContainerGap(318, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /* Triggered when the "Add" button is pressed. Adds an employee with the inputted
       attributes to the hash table*/
    private void addTheNewEmployee(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTheNewEmployee
        // TODO add your handling code here:
        
        int theEmpNum = 0; // initializing and assigning a value to theEmpNum 
        
        if (!firstNameText.getText().isEmpty() && !lastNameText.getText().isEmpty()
                && !empNumText.getText().isEmpty()) {
            
           if ((!firstNameText.getText().matches("[a-zA-Z]+")) ||
              (!lastNameText.getText().matches("[a-zA-Z]+"))) {
               
               JOptionPane.showMessageDialog(this, "Employees' names"
               + " must only consist of letters!", "Invalid Employee Name", 
               JOptionPane.WARNING_MESSAGE);
               return;
           }
            
            String theFirstName = firstNameText.getText();
            theFirstName = theFirstName.substring(0, 1).toUpperCase() +
                           theFirstName.substring(1).toLowerCase();
            String theLastName = lastNameText.getText();
            theLastName = theLastName.substring(0, 1).toUpperCase() +
                           theLastName.substring(1).toLowerCase();
            
            try {
                
                if ((empNumText.getText().length() != 6)) {
                    JOptionPane.showMessageDialog(this, "The employee number"
                    + " must be 6 digits!", "Invalid Employee Number",
                    JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                theEmpNum = Integer.parseInt(empNumText.getText());

                int targetBucket = mainHT.calcBucket(theEmpNum);

                for (int i = 0; i < mainHT.buckets[targetBucket].size(); i++) {
                    if (mainHT.buckets[targetBucket].get(i).empNum == theEmpNum) {
                        JOptionPane.showMessageDialog(this, "That employee number is"
                                + " already in use. Please choose another one.", "Duplicate Warning",
                                JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                }
            }
            
            catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "The employee number"
                + " must be 6 digits!", "Invalid Employee Number",
                JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // FULL TIME EMPLOYEE
            if (fullTimeButton.isSelected()) { 
                
                if (annualSalaryText.getText().isEmpty() || fuillTimeDRText.getText().isEmpty()) {
                    return;
                }
                
                try {
                    
                    String strSalary = annualSalaryText.getText();
                    double dSalary = Double.parseDouble(strSalary);

                    String strDR = fuillTimeDRText.getText();
                    double dDR = Double.parseDouble(strDR);

                    if ((Double.parseDouble(annualSalaryText.getText()) <= 0)
                            || (Double.parseDouble(fuillTimeDRText.getText()) <= 0)
                            || (Double.parseDouble(fuillTimeDRText.getText()) >= 1)) {

                        JOptionPane.showMessageDialog(this, "The salary and/or deduction rate"
                                + " inputs are invalid!", "Invalid Input Values",
                                JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    
                    FTE theFTE = new FTE(theEmpNum, theFirstName, theLastName,
                                         dDR, dSalary);
                    
                    mainHT.addEmployee(theFTE);
                }
                
                catch (NumberFormatException e) {
                    
                    JOptionPane.showMessageDialog(this, "The salary and deduction rate"
                    + " info must be numeric!.", "Invalid Input Values",
                    JOptionPane.WARNING_MESSAGE);
                    return;
                } 
            }
            
            // PART TIME EMPLOYEE
            else if (partTimeButton.isSelected()) {
                
                if (hWText.getText().isEmpty() || hPWText.getText().isEmpty() ||
                   wPYText.getText().isEmpty() || partTimeDRText.getText().isEmpty()) {
                    return;
                }
                
                try {
                    
                    // Get the hourly wage, hours per week, weeks per year
                    // Instantiate an PTE with the info for that employee
                    // Add that employee to the hash table
                    
                    String strHW = hWText.getText();
                    double dHW = Double.parseDouble(strHW);

                    String strHPW = hPWText.getText();
                    double dHPW = Double.parseDouble(strHPW);

                    String strWPY = wPYText.getText();
                    double dWPY = Double.parseDouble(strWPY);

                    String strDR = partTimeDRText.getText();
                    double dDR = Double.parseDouble(strDR);

                    if ((Double.parseDouble(hWText.getText()) <= 0)
                            || (Double.parseDouble(hPWText.getText()) <= 0)
                            || (Double.parseDouble(hPWText.getText()) > 168)
                            || (Double.parseDouble(wPYText.getText()) <= 0)
                            || (Double.parseDouble(wPYText.getText()) > 52)
                            || (Double.parseDouble(partTimeDRText.getText()) <= 0)
                            || (Double.parseDouble(partTimeDRText.getText()) >= 1)) {

                        JOptionPane.showMessageDialog(this, "The salary and/or deduction rate"
                                + " inputs are invalid!", "Invalid Input Values",
                                JOptionPane.WARNING_MESSAGE);
                        return;
                    } 
                    
                    else if (((Double.parseDouble(hPWText.getText()) % 0.5 > 0))
                            || ((Double.parseDouble(wPYText.getText()) % 0.5 > 0))) {

                        JOptionPane.showMessageDialog(this, "Please round the hours"
                                + " per week, and weeks per year inputs to the nearest 0.5!", "Invalid Input Values",
                                JOptionPane.WARNING_MESSAGE);
                        return;
                    }
                    
                    PTE thePTE = new PTE(theEmpNum, theFirstName, theLastName,
                            dDR, dHW, dHPW, dWPY);

                    mainHT.addEmployee(thePTE);
                }
                
                catch (NumberFormatException e) {
                    
                    JOptionPane.showMessageDialog(this, "The salary and deduction rate"
                    + " info must be numeric!.", "Invalid Input Values",
                    JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
            
            else {
                return;
            }
        
        }
        
        else {
            return;
        }
        
        JOptionPane.showMessageDialog(this,
                "The employee has been added to the system!",
                "Success",
                JOptionPane.PLAIN_MESSAGE);
        
        empNumText.setText("");
        firstNameText.setText("");
        lastNameText.setText("");
        annualSalaryText.setText("");
        hWText.setText("");
        hPWText.setText("");
        wPYText.setText("");
        partTimeDRText.setText("");
        fuillTimeDRText.setText("");
        buttonGroup1.clearSelection();
        fullTimeInternalFrame.setVisible(false);  // Hide the FTE internal jFrame
        partTimeInternalFrame.setVisible(false);  // Hide the PTE internal jFrame
    }//GEN-LAST:event_addTheNewEmployee

    // Makes the FT IF visible, and hides the PT IF
    private void FTERadioButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTERadioButtonClicked
        // TODO add your handling code here:
        partTimeInternalFrame.setVisible(false);  // PTE stuff
        fullTimeInternalFrame.setVisible(true);   // FTE stuff
    }//GEN-LAST:event_FTERadioButtonClicked

    // Makes the PT IF visible, and hides the FT IF
    private void PTERadioButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTERadioButtonClicked
        // TODO add your handling code here:
        fullTimeInternalFrame.setVisible(false);  // FTE stuff
        partTimeInternalFrame.setVisible(true);   // PTE stuff
    }//GEN-LAST:event_PTERadioButtonClicked

    // Triggered when the "Exit" button is pressed. Closes the JFrame.
    private void exitAddNewEmployee(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAddNewEmployee
        // TODO add your handling code here:
        this.dispose(); // Make this window disappear
    }//GEN-LAST:event_exitAddNewEmployee

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployee_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployee_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployee_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNewEmployee_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNewEmployee_jFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel annualSalaryLabel;
    private javax.swing.JTextField annualSalaryText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel empNumLabel;
    private javax.swing.JTextField empNumText;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JTextField fuillTimeDRText;
    private javax.swing.JRadioButton fullTimeButton;
    private javax.swing.JLabel fullTimeDRLabel;
    private javax.swing.JInternalFrame fullTimeInternalFrame;
    private javax.swing.JLabel hPWLabel;
    private javax.swing.JTextField hPWText;
    private javax.swing.JLabel hWLabel;
    private javax.swing.JTextField hWText;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JRadioButton partTimeButton;
    private javax.swing.JLabel partTimeDRLabel;
    private javax.swing.JTextField partTimeDRText;
    private javax.swing.JInternalFrame partTimeInternalFrame;
    private javax.swing.JLabel wPYLabel;
    private javax.swing.JTextField wPYText;
    // End of variables declaration//GEN-END:variables

}