import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ButtonGroup;
import javax.swing.DefaultListModel;
import javax.swing.DefaultListSelectionModel;
import javax.swing.JOptionPane;

public class EditEmployeeInfo_jFrame extends javax.swing.JFrame {
    
    private MyHashTable mainHT;  // This contains the ref value for theHT of MainJFrame.
    private final ButtonGroup group = new ButtonGroup();
    
     //Creates new form EditEmployeeInfo_jFrame
    public EditEmployeeInfo_jFrame() {
        initComponents();
        
        group.add(partTimeButton);
        group.add(fullTimeButton);
                
        firstNameLabel.setVisible(false);
        lastNameLabel.setVisible(false);
        empNumLabel.setVisible(false);
        firstNameText.setVisible(false);
        lastNameText.setVisible(false);
        employeeNumText.setVisible(false);
        partTimeButton.setVisible(false);
        fullTimeButton.setVisible(false);
        fTInternalFrame.setVisible(false);  // Hide the FTE internal jFrame
        pTInternalFrame.setVisible(false);  // Hide the PTE internal jFrame
        saveEmployeeButton.setVisible(false);   
        employeeList.setSelectionMode(DefaultListSelectionModel.SINGLE_SELECTION);
        employeeList.setVisible(false);
        employeeListScrollPane.setVisible(false);
        empNumText.setVisible(false);
        editEmployeePromptLabel.setVisible(false);
        editEmployeeButton.setVisible(false);
        dividerLabel.setVisible(false);
    }

    public void setMainHT(MyHashTable theRefVal) {
        mainHT = theRefVal;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        partTimeButton = new javax.swing.JRadioButton();
        firstNameText = new javax.swing.JTextField();
        fTInternalFrame = new javax.swing.JInternalFrame();
        annualSalaryLabel = new javax.swing.JLabel();
        annualSalaryText = new javax.swing.JTextField();
        fTDRLabel = new javax.swing.JLabel();
        fTDRText = new javax.swing.JTextField();
        empNumLabel = new javax.swing.JLabel();
        firstNameLabel = new javax.swing.JLabel();
        pTInternalFrame = new javax.swing.JInternalFrame();
        hWLabel = new javax.swing.JLabel();
        hPWLabel = new javax.swing.JLabel();
        wPYLabel = new javax.swing.JLabel();
        hWText = new javax.swing.JTextField();
        hPWText = new javax.swing.JTextField();
        wPYText = new javax.swing.JTextField();
        pTDRLabel = new javax.swing.JLabel();
        pTDRText = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        employeeNumText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        saveEmployeeButton = new javax.swing.JButton();
        exitEditEmployeeButton = new javax.swing.JButton();
        fullTimeButton = new javax.swing.JRadioButton();
        editEmployeeLabel = new javax.swing.JLabel();
        empNumText = new javax.swing.JTextField();
        editEmployeeButton = new javax.swing.JButton();
        dividerLabel = new javax.swing.JLabel();
        employeeNumberSearchButton = new javax.swing.JRadioButton();
        employeeListButton = new javax.swing.JRadioButton();
        editEmployeePromptLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        employeeListScrollPane = new javax.swing.JScrollPane();
        employeeList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        partTimeButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        partTimeButton.setText("Part time");
        partTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PTERadioButtonClicked(evt);
            }
        });

        firstNameText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        fTInternalFrame.setVisible(true);

        annualSalaryLabel.setText("Annual Salary");

        annualSalaryText.setToolTipText("Gross Annual Salary");

        fTDRLabel.setText("Deduction Rate");

        javax.swing.GroupLayout fTInternalFrameLayout = new javax.swing.GroupLayout(fTInternalFrame.getContentPane());
        fTInternalFrame.getContentPane().setLayout(fTInternalFrameLayout);
        fTInternalFrameLayout.setHorizontalGroup(
            fTInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fTInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fTInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fTInternalFrameLayout.createSequentialGroup()
                        .addComponent(fTDRLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fTDRText, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fTInternalFrameLayout.createSequentialGroup()
                        .addComponent(annualSalaryLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(annualSalaryText, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        fTInternalFrameLayout.setVerticalGroup(
            fTInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fTInternalFrameLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fTInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(annualSalaryLabel)
                    .addComponent(annualSalaryText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fTInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fTDRLabel)
                    .addComponent(fTDRText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(61, Short.MAX_VALUE))
        );

        empNumLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        empNumLabel.setText("Employee Number");
        empNumLabel.setToolTipText("Enter a six digit employee number (e.g. 123456)");

        firstNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        firstNameLabel.setText("First Name");

        pTInternalFrame.setVisible(true);

        hWLabel.setText("Hourly wage");

        hPWLabel.setText("Hours per week");

        wPYLabel.setText("Weeks per year");

        pTDRLabel.setText("Deduction Rate");

        javax.swing.GroupLayout pTInternalFrameLayout = new javax.swing.GroupLayout(pTInternalFrame.getContentPane());
        pTInternalFrame.getContentPane().setLayout(pTInternalFrameLayout);
        pTInternalFrameLayout.setHorizontalGroup(
            pTInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTInternalFrameLayout.createSequentialGroup()
                .addGroup(pTInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTInternalFrameLayout.createSequentialGroup()
                        .addGroup(pTInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pTInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(wPYLabel)
                                .addComponent(hPWLabel))
                            .addComponent(hWLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pTInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(hPWText, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(wPYText)
                            .addComponent(hWText)))
                    .addGroup(pTInternalFrameLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pTDRLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pTDRText, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        pTInternalFrameLayout.setVerticalGroup(
            pTInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTInternalFrameLayout.createSequentialGroup()
                .addGroup(pTInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hWLabel)
                    .addComponent(hWText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pTInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hPWLabel)
                    .addComponent(hPWText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(pTInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(wPYLabel)
                    .addComponent(wPYText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(pTInternalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pTDRLabel)
                    .addComponent(pTDRText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        lastNameLabel.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lastNameLabel.setText("Last Name");

        employeeNumText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        employeeNumText.setToolTipText("Enter a six digit employee number (e.g. 123456)");
        employeeNumText.setMinimumSize(new java.awt.Dimension(60, 20));

        lastNameText.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lastNameText.setMinimumSize(new java.awt.Dimension(60, 20));

        saveEmployeeButton.setText("Save");
        saveEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmployeeInfo(evt);
            }
        });

        exitEditEmployeeButton.setText("Exit");
        exitEditEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitEditEmployeeInfo(evt);
            }
        });

        fullTimeButton.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        fullTimeButton.setText("Full time");
        fullTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FTERadioButtonClicked(evt);
            }
        });

        editEmployeeLabel.setText("Would you like to find the employee to edit by searching for them using their employee number, or scrolling through a list of all the employees?");

        editEmployeeButton.setText("Edit Employee");
        editEmployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findEmployee(evt);
            }
        });

        dividerLabel.setText("——————————————————————————————————");

        buttonGroup1.add(employeeNumberSearchButton);
        employeeNumberSearchButton.setText("Employee Number Search");
        employeeNumberSearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empNumOptionPressed(evt);
            }
        });

        buttonGroup1.add(employeeListButton);
        employeeListButton.setText("List of Employees");
        employeeListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                empListOptionPressed(evt);
            }
        });

        editEmployeePromptLabel.setText("Prompt to user");

        employeeListScrollPane.setViewportView(employeeList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(employeeListScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(employeeListScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pTInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(fTInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(editEmployeeLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(employeeNumberSearchButton)
                                .addGap(18, 18, 18)
                                .addComponent(employeeListButton)
                                .addGap(18, 18, 18)
                                .addComponent(exitEditEmployeeButton))
                            .addComponent(editEmployeePromptLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empNumText, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(editEmployeeButton)
                            .addComponent(dividerLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(partTimeButton)
                                    .addComponent(lastNameLabel)
                                    .addComponent(firstNameLabel)
                                    .addComponent(empNumLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(employeeNumText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lastNameText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(fullTimeButton))))
                        .addContainerGap(21, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(saveEmployeeButton)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(editEmployeeLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employeeNumberSearchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeListButton, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitEditEmployeeButton))
                .addGap(18, 18, 18)
                .addComponent(editEmployeePromptLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(empNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(editEmployeeButton)
                .addGap(18, 18, 18)
                .addComponent(dividerLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstNameLabel)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastNameLabel))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(empNumLabel)
                    .addComponent(employeeNumText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(partTimeButton)
                    .addComponent(fullTimeButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fTInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pTInternalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveEmployeeButton)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Creates a JList with all the employees in the system
    private void empListOptionPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empListOptionPressed
        // TODO add your handling code here:

        DefaultListModel<String> listModel = new DefaultListModel<>();

        for (int i = 0; i < mainHT.buckets.length; i++) {
            for (int j = 0; j < mainHT.buckets[i].size(); j++) {

                EmployeeInfo theEmp = mainHT.buckets[i].get(j);
                listModel.addElement(theEmp.firstName + " " + theEmp.lastName
                    + " (" + (theEmp.empNum) + ")");
            }
        }

        editEmployeePromptLabel.setText("From the list below, select the employee whose info you want to get: ");
        editEmployeePromptLabel.setVisible(true);
        employeeList.setModel(listModel);
        employeeList.setVisible(true);
        employeeListScrollPane.setVisible(true);
        editEmployeeButton.setVisible(true);
        empNumText.setVisible(false);
        
        firstNameLabel.setVisible(false);
        lastNameLabel.setVisible(false);
        empNumLabel.setVisible(false);
        firstNameText.setVisible(false);
        lastNameText.setVisible(false);
        employeeNumText.setVisible(false);
        partTimeButton.setVisible(false);
        fullTimeButton.setVisible(false);
        fTInternalFrame.setVisible(false);  // Hide the FTE internal jFrame
        pTInternalFrame.setVisible(false);  // Hide the PTE internal jFrame
        saveEmployeeButton.setVisible(false);
    }//GEN-LAST:event_empListOptionPressed

    // Identifies the employee that the user wants to edit, and allows them to edit their attributes
    private void findEmployee(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findEmployee
        // TODO add your handling code here:

        EmployeeInfo theEmp = null;

        if (employeeNumberSearchButton.isSelected()) {

            if (!empNumText.getText().isEmpty()) {

                try {

                    int theEmpNum = Integer.parseInt(empNumText.getText());
                    theEmp = mainHT.removeEmployee(theEmpNum);

                }

                catch (NumberFormatException e) {

                    JOptionPane.showMessageDialog(this, "The employee number"
                    + " must be 6 digits!", "Invalid Employee Number",
                    JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
        }

        else if (employeeListButton.isSelected()) {
            
            List selectedEmployees = employeeList.getSelectedValuesList();

            if (!selectedEmployees.isEmpty()) {

                for (int i = 0; i < selectedEmployees.size(); i++) {

                    String currentEmployee = (String) selectedEmployees.get(i);

                    Pattern pattern = Pattern.compile("[0-9]{6}");
                    Matcher matcher = pattern.matcher(currentEmployee);
                    matcher.find();
                    int theEmpNum = Integer.parseInt(currentEmployee.substring(matcher.start(), 
                                                     matcher.end()));
                    theEmp = mainHT.removeEmployee(theEmpNum);
                }
            }
        }

        else {

            JOptionPane.showMessageDialog(this, "Please choose a method to" +
                " find the employee(s) you want to edit!", "Choose Search Method!",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (theEmp != null) {
            
            dividerLabel.setVisible(true);
            firstNameText.setText(theEmp.firstName);
            lastNameText.setText(theEmp.lastName);
            employeeNumText.setText(String.valueOf(theEmp.empNum));

            if (theEmp instanceof PTE) {

                PTE PTEmp = (PTE) theEmp;

                partTimeButton.doClick();
                hWText.setText(String.valueOf(PTEmp.hourlyWage));
                hPWText.setText(String.valueOf(PTEmp.hoursPerWeek));
                wPYText.setText(String.valueOf(PTEmp.weeksPerYear));
                pTInternalFrame.setVisible(true);  // Hide the PTE internal jFrame
                pTDRText.setText(String.valueOf(PTEmp.deductRate));
            }

            else {

                FTE FTEmp = (FTE) theEmp;

                fullTimeButton.doClick();
                annualSalaryText.setText(String.valueOf(FTEmp.yearlySalary));
                fTInternalFrame.setVisible(true);  // Hide the FTE internal jFrame
                fTDRText.setText(String.valueOf(FTEmp.deductRate));
            }

            firstNameLabel.setVisible(true);
            lastNameLabel.setVisible(true);
            empNumLabel.setVisible(true);
            firstNameText.setVisible(true);
            lastNameText.setVisible(true);
            employeeNumText.setVisible(true);
            partTimeButton.setVisible(true);
            fullTimeButton.setVisible(true);
            saveEmployeeButton.setVisible(true);
        }

        else {
            JOptionPane.showMessageDialog(this, "That employee number is"
                + " not in the database. Please make sure no typos were made",
                "Employee Number Not Found", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_findEmployee

    // Sets up a JTextField where the user can input an employee number in order to identify an employee to edit
    private void empNumOptionPressed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_empNumOptionPressed
        // TODO add your handling code here:

        editEmployeePromptLabel.setText("Enter the employee number of the employee whose info you want: ");
        editEmployeePromptLabel.setVisible(true);
        empNumText.setVisible(true);
        editEmployeeButton.setVisible(true);
        employeeList.setVisible(false);
        employeeListScrollPane.setVisible(false);
        
        firstNameLabel.setVisible(false);
        lastNameLabel.setVisible(false);
        empNumLabel.setVisible(false);
        firstNameText.setVisible(false);
        lastNameText.setVisible(false);
        employeeNumText.setVisible(false);
        partTimeButton.setVisible(false);
        fullTimeButton.setVisible(false);
        fTInternalFrame.setVisible(false);  // Hide the FTE internal jFrame
        pTInternalFrame.setVisible(false);  // Hide the PTE internal jFrame
        saveEmployeeButton.setVisible(false);
    }//GEN-LAST:event_empNumOptionPressed

    // Makes the FT IF visible, and hids the PT IF
    private void FTERadioButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FTERadioButtonClicked
        // TODO add your handling code here:
        pTInternalFrame.setVisible(false);  // PTE stuff
        fTInternalFrame.setVisible(true);   // FTE stuff
    }//GEN-LAST:event_FTERadioButtonClicked

    // Triggered when the "Exit" button is pressed. Closes the JFrame.
    private void exitEditEmployeeInfo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitEditEmployeeInfo
        // TODO add your handling code here:
        this.dispose(); // exit edit frame
    }//GEN-LAST:event_exitEditEmployeeInfo

    // Saves the edited employee info in the hash table
    private void updateEmployeeInfo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmployeeInfo
        // TODO add your handling code here:

        if (!firstNameText.getText().isEmpty() && !lastNameText.getText().isEmpty()
            && !employeeNumText.getText().isEmpty()) {

            if (employeeNumText.getText().length() != 6) {
                JOptionPane.showMessageDialog(this, "The employee number"
                    + " must have 6 digits!", "Invalid Employee Number",
                    JOptionPane.WARNING_MESSAGE);
                return;
            }

            int theEmpNum = Integer.parseInt(employeeNumText.getText());

            int targetBucket = mainHT.calcBucket(theEmpNum);

            for (int i = 0; i < mainHT.buckets[targetBucket].size(); i++) {
                if (mainHT.buckets[targetBucket].get(i).empNum == theEmpNum) {
                    JOptionPane.showMessageDialog(this, "That employee number is"
                        + " already in use. Please choose another one.", "Duplicate Warning",
                        JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }

            String theFirstName = firstNameText.getText();
            String theLastName = lastNameText.getText();

            // FULL TIME EMPLOYEE
            if (fullTimeButton.isSelected() && !annualSalaryText.getText().isEmpty()) {

                String strSalary = annualSalaryText.getText();
                double dSalary = Double.parseDouble(strSalary);

                String strDR = fTDRText.getText();
                double dDR = Double.parseDouble(strDR);

                FTE theFTE = new FTE(theEmpNum, theFirstName, theLastName,
                    dDR, dSalary);
                //System.out.println("Salary of the FTE is " + dSalary);

                mainHT.addEmployee(theFTE);
            }

            // PART TIME EMPLOYEE
            else if (partTimeButton.isSelected() && (!hWText.getText().isEmpty()
                || !hPWText.getText().isEmpty() || !wPYText.getText().isEmpty())) {

                // Get the hourly wage, hours per week, weeks per year
                // Instantiate an PTE with the info for that employee
                // Add that employee to the hash table

                String strHW = hWText.getText();
                double dHW = Double.parseDouble(strHW);

                String strHPW = hPWText.getText();
                double dHPW = Double.parseDouble(strHPW);

                String strWPY = wPYText.getText();
                double dWPY = Double.parseDouble(strWPY);

                String strDR = pTDRText.getText();
                double dDR = Double.parseDouble(strDR);

                PTE thePTE = new PTE(theEmpNum, theFirstName, theLastName,
                    dDR, dHW, dHPW, dWPY);

                mainHT.addEmployee(thePTE);
            }   

            else {
                return;
            }
        }

        else {
            return;
        }

        JOptionPane.showMessageDialog(this, "The employee's "
        + "info has been saved!", "Success", JOptionPane.PLAIN_MESSAGE);

        editEmployeePromptLabel.setVisible(false);
        employeeList.setVisible(false);
        employeeListScrollPane.setVisible(false);
        empNumText.setVisible(false);
        editEmployeeButton.setVisible(false);
        buttonGroup1.clearSelection();
        
        employeeNumText.setText("");
        firstNameText.setText("");
        lastNameText.setText("");
        annualSalaryText.setText("");
        hWText.setText("");
        hPWText.setText("");
        wPYText.setText("");
        
        dividerLabel.setVisible(false);
        firstNameLabel.setVisible(false);
        lastNameLabel.setVisible(false);
        empNumLabel.setVisible(false);
        firstNameText.setVisible(false);
        lastNameText.setVisible(false);
        employeeNumText.setVisible(false);
        partTimeButton.setVisible(false);
        fullTimeButton.setVisible(false);
        fTInternalFrame.setVisible(false);  // Hide the FTE internal jFrame
        pTInternalFrame.setVisible(false);  // Hide the PTE internal jFrame
        saveEmployeeButton.setVisible(false);
    }//GEN-LAST:event_updateEmployeeInfo

    // Makes the PT IF visible, and hids the FT IF
    private void PTERadioButtonClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PTERadioButtonClicked
        // TODO add your handling code here:
        fTInternalFrame.setVisible(false);  // FTE stuff
        pTInternalFrame.setVisible(true);   // PTE stuff
    }//GEN-LAST:event_PTERadioButtonClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeInfo_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeInfo_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeInfo_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditEmployeeInfo_jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditEmployeeInfo_jFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel annualSalaryLabel;
    private javax.swing.JTextField annualSalaryText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel dividerLabel;
    private javax.swing.JButton editEmployeeButton;
    private javax.swing.JLabel editEmployeeLabel;
    private javax.swing.JLabel editEmployeePromptLabel;
    private javax.swing.JLabel empNumLabel;
    private javax.swing.JTextField empNumText;
    private javax.swing.JList<String> employeeList;
    private javax.swing.JRadioButton employeeListButton;
    private javax.swing.JScrollPane employeeListScrollPane;
    private javax.swing.JTextField employeeNumText;
    private javax.swing.JRadioButton employeeNumberSearchButton;
    private javax.swing.JButton exitEditEmployeeButton;
    private javax.swing.JLabel fTDRLabel;
    private javax.swing.JTextField fTDRText;
    private javax.swing.JInternalFrame fTInternalFrame;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JRadioButton fullTimeButton;
    private javax.swing.JLabel hPWLabel;
    private javax.swing.JTextField hPWText;
    private javax.swing.JLabel hWLabel;
    private javax.swing.JTextField hWText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JLabel pTDRLabel;
    private javax.swing.JTextField pTDRText;
    private javax.swing.JInternalFrame pTInternalFrame;
    private javax.swing.JRadioButton partTimeButton;
    private javax.swing.JButton saveEmployeeButton;
    private javax.swing.JLabel wPYLabel;
    private javax.swing.JTextField wPYText;
    // End of variables declaration//GEN-END:variables
}
